services:
  video_in:
    image: containers.openfilter.io/plainsightai/openfilter-video-in:v0.1.10
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-}
      FILTER_ID: VideoIn
      FILTER_SOURCES: file:///video.mp4!sync!loop
      FILTER_OUTPUTS: tcp://*
    volumes:
      - ./data/sample-video.mp4:/video.mp4:ro

  chatgpt_annotator_filter:
    build:
      context: .
      dockerfile: Dockerfile
    image: filter-chatgpt-annotator:local
    pull_policy: never
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-}
      FILTER_ID: ChatgptAnnotatorFilter
      FILTER_SOURCES: tcp://video_in
      FILTER_OUTPUTS: tcp://*
      FILTER_MQ_LOG: pretty
      FILTER_CHATGPT_API_KEY: 'sk-open-ai-key'
      FILTER_PROMPT: '/simple_salad_prompt_bb_v3.txt'
      FILTER_OUTPUT_SCHEMA: '{"avocado":{"present":false,"confidence":0.0,"bbox":null},"lettuce":{"present":false,"confidence":0.0,"bbox":null},"tomato":{"present":false,"confidence":0.0,"bbox":null}}'
    volumes:
      - ./prompts/simple_salad_prompt_bb_v3.txt:/simple_salad_prompt_bb_v3.txt:ro

  webvis:
    image: containers.openfilter.io/plainsightai/openfilter-webvis:v0.1.10
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-}
      FILTER_ID: Webvis
      FILTER_SOURCES: tcp://chatgpt_annotator_filter
    ports:
      - 8001:8000